backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"   # where uploaded files are stored in repo
public_folder: "/uploads"        # how they are accessed in browser

collections:
  - name: "gallery"
    label: "Portfolio Gallery"
    label_singular: "Image"
    folder: "content/gallery"
    create: true
    format: "json"       # <--- save as JSON instead of markdown
    extension: "json"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Weddings", "Baptisms", "Events", "Birthdays", "Passport"] }
      - { label: "Image", name: "image", widget: "image" }